### ISSUE TITLE
[Submission] search_spot icon

### ISSUE THREAD

**Issue by HYPD** [Shopify/polaris-icons#153]
#### Slack handle
@danross

#### What team / project is this for?
Polaris Tooling - Polaris Icons

#### How will this icon be used?
We'd like to use this in the empty state in Polaris Icons.
<img width="1680" alt="screen shot 2019-02-15 at 1 50 16 pm" src="https://user-images.githubusercontent.com/970304/52878431-9a61d100-312a-11e9-861a-cbf28487ef44.png">

#### Link your branch from Abstract
https://share.goabstract.com/76394406-667a-4ae4-9f34-1c78cca1df92

#### Icon SVG
https://drive.google.com/open?id=1xN77t53z50DtmFsTfCijNjREYmnxvhqi

As Spot icons don't need metadata yet I have deleted the rest of the content for this issue.

**Comment by kaelig** [comment]
Closing this as this is low visibility and low impact. Feel free to pick up if you have spare cycles and want to have a little fun, but it's not a priority.
