### ISSUE TITLE
[Request] Minor `Full screen`

### ISSUE THREAD

**Issue by alekmackie** [Shopify/polaris-icons#167]
#### What team / project is this for?
Analytics

#### What’s your request?
Right now, Analytics uses this icon (not currently in Polaris, though I think I remember it from a couple years ago) for:

![](https://screenshot.click/3x0gh.jpg)

This says "external link" for me.  And this action doesn't open a new tab, or redirect to something external.  I feel something that says more specifically "maximize" or "full screen" would work better:

![](https://screenshot.click/Screen_Shot_2019-02-25_at_2.36.39_PM.png)

**Comment by kaelig** [comment]
Closing this submission for inactivity as it was last updated more than 1/2 year ago. Please reopen if this is still current.
