### ISSUE TITLE
Broken sound (major) icon in Sketch file

### ISSUE THREAD

**Issue by ouellettejordan** [Shopify/polaris-icons#343]
### Slack handle

@jordanouellette

### Original icon name

sound (major)

### Icon bug

`Sound` icon (major) in `lighter` is filled but should be a stroke icon like the `Lightest` version to the right of it. See screenshot below. 

![Screen Shot 2019-05-02 at 3 32 33 PM](https://user-images.githubusercontent.com/12194323/57106734-28962e00-6cfc-11e9-9323-c2484095d73c.png)

cc @HYPD

**Comment by kaelig** [comment]
Closing this as we aren't going to keep the Sketch Icon Kit up to date going forward.
