### ISSUE TITLE
Data security and privacy icon

### ISSUE THREAD

**Issue by davekilljoy** [Shopify/polaris-icons#53]
#### What’s your name?
David Stubbs

#### Slack handle
@danforth

#### What team / project is this for?
https://unicorn.shopify.io/projects/4647

#### When would you like it by?
09/05/2018

#### What’s your request?
The ask is that we create an icon specifically for data privacy that we can use across Shopify in areas where data could be sensitive.

A little context

GDPR is a new European legislation coming into effect on May 25th that states anyone has the right to own their own data irrespective of what system it is on. This means merchants and buyers have the right to ask for their data to be deleted.

As GDPR approaches we're looking for ways to communicate the implications to the merchant, and give them trust that we are very well suited to manage their sensitive data. Part of that will be to have a high level concept that lives across all areas where data trust is important.

Apple has a great example of this - they have a consistent icon that shows up in areas where data might be sensitive to ensure to the user that it's safe.

![duvapdxxkaasej1-1](https://user-images.githubusercontent.com/1523373/39538815-06e38b5a-4e0c-11e8-9038-c7cec6a2c27c.jpg)

![duu7otiwsae6nuj](https://user-images.githubusercontent.com/1523373/39538958-6a0ef980-4e0c-11e8-8cf2-def39bba81ab.jpg)

@nicklooijmans @jessebc @kpeatt

**Comment by kaelig** [comment]
Closing this as it hasn't seen any activity over the past year. Feel free to reopen if you have the bandwidth to own this piece of work.
