### ISSUE TITLE
Polaris Icons UI CDN Bootstrap

### ISSUE THREAD

**Issue by Benwebdev** [Shopify/polaris-icons#626]
Do I have permission to take the icons and make a cdn for the icons like font-awesome, then I can add it to my version of polaris in bootstrap?

**Comment by HYPD** [comment]
Hi @Benwebdev. Our icons are already being served over a CDN 
https://unpkg.com/@shopify/polaris-icons@3.4.0/images/

Does this answer your question?

**Comment by Benwebdev** [comment]
Ahhhhhh. 

Okay. 

Thank you 💃
