### ISSUE TITLE
[Request] Custom sale icon for POS

### ISSUE THREAD

**Issue by AdamWhitcroft** [Shopify/polaris-icons#645]
### Slack handle

@toby

### What team and project is this for?

POS

### How will this icon be used?

We renamed "Quick sale" to "Add custom sale". The lightning bolt icon that we use right now is not working anymore in this new context. 

The new icon should also follow the same aesthetic we created for all icons in POS Next.

### Major or minor?

Major

### Number of icons?

1

### Links / supporting content

https://drive.google.com/a/shopify.com/file/d/1T5tGAFRzcuiZSqMv7PNk2Hv8nPBDWAw6/view?usp=sharing

**Comment by AdamWhitcroft** [comment]
@bytino CC'ing you here.

**Comment by AdamWhitcroft** [comment]
@bytino how're you getting on with these?

**Comment by kaelig** [comment]
Closing this as it has been stale for almost 2 months.
