### ISSUE TITLE
[Request] Paragraph alignment icons

### ISSUE THREAD

**Issue by AdamWhitcroft** [Shopify/polaris-icons#646]
### Slack handle

`@arthur`

### What team and project is this for?

Email

### How will this icon be used?

Icons for text alignment: left, center & right.

### Major or minor?

Unsure

### Number of icons?

3

**Comment by AdamWhitcroft** [comment]
@arthurgouveia CC'ing you here.

**Comment by arthurgouveia** [comment]
![https://media.giphy.com/media/WSs7hJYfg4WIGMgMJj/giphy.gif](https://media.giphy.com/media/WSs7hJYfg4WIGMgMJj/giphy.gif)

**Comment by AdamWhitcroft** [comment]
@arthurgouveia are we good to close this?

**Comment by arthurgouveia** [comment]
@AdamWhitcroft I'm waiting for @kaelig to approve https://github.com/Shopify/polaris-icons/pull/647.

I'm assuming we only close after merge + deploy. I have no idea on what's the workflow used on this project
