### ISSUE TITLE
Update the link to request a new icon

### ISSUE THREAD

**Issue by allylane** [Shopify/polaris-icons#650]
On this screen:

![Screenshot 2019-08-14 11 03 05](https://user-images.githubusercontent.com/17570703/63032087-2444e980-be83-11e9-940b-fc7b0edae4a6.png)

Could we update the request link to go here?:
https://github.com/Shopify/creative-direction/issues/new/choose

**Comment by kaelig** [comment]
Closing this as the link was updated to point to the icon submission Google doc. Please reopen if this should be changed again.
