### ISSUE TITLE
Create abandoned checkout icon that we can use in Shopify Mobile's Orders tab

### ISSUE THREAD

**Issue by batlounis** [Shopify/polaris-icons#683]
Attached is the unfiltered version for reference 😅
![IMG_1178](https://user-images.githubusercontent.com/46444/66078854-d7030100-e530-11e9-82a9-9cab97a894d9.jpeg)

**Comment by AdamWhitcroft** [comment]
Heyo! So this icon already exists in our icon kit, named `Abandoned cart`.

<img width="490" alt="Screen Shot 2019-10-04 at 3 54 35 PM" src="https://user-images.githubusercontent.com/861526/66235962-51618b80-e6bf-11e9-9cbd-7ebab18dcd3b.png">

**Comment by aimeejoelleanderson** [comment]
Nice! If you're happy to continue using that icon, could you please ping me a pdf of the icon so I can use it in the mobile app?

**Comment by BPScott** [comment]
The polaris_icons gem contains all icons in PDF format, suitable for mobile app consumption. See  https://github.com/Shopify/polaris-icons/tree/master/packages-ruby/polaris_icons for more info

**Comment by kaelig** [comment]
Closing this as it hasn't had any activity in a month. Feel free to reopen if you require further assistance on it ❤️
