### ISSUE TITLE
[Suggestion] Icons referral-code & referral

### ISSUE THREAD

**Issue by tarynmusgrave** [Shopify/polaris-icons#685]
### Slack handle

@tarynmusgrave

### What team and project is this for?

Logistics - Admin

### How will this icon be used?

These icons are used for porting ERB to React.

### Icon SVG

https://github.com/Shopify/shopify/blob/master/app/assets/svg/admin-fresh/shared/referral-code.svg

https://github.com/Shopify/shopify/blob/master/app/assets/svg/admin-fresh/shared/referral.svg

**Comment by kaelig** [comment]
@AdamWhitcroft did you author these icons, by any chance?
