### ISSUE TITLE
Capital icon

### ISSUE THREAD

**Issue by kathleen-ships** [Shopify/polaris-icons#77]
#### What’s your name?
Kathleen Robertson

#### Slack handle
@kathleen.robertson

#### What team / project is this for?
Shopify Capital

#### When would you like it by?
07/09/2018 (Flexible on the date)

#### What’s your request?
Need an icon for Capital that would work in the Settings area of the admin. It would need to work in context with other money services or products (like Billing, Payments, Taxes etc). 
The icon would need to work for multiple Capital use cases. Such as: A merchant being offer funding, and merchant's who currently have funding with us. 

Example:
<img width="812" alt="screen shot 2018-08-29 at 8 19 34 am" src="https://user-images.githubusercontent.com/28788118/44787148-5242f800-ab64-11e8-8200-5c49a2c005ce.png">

**Comment by kaelig** [comment]
Superceded by #655
