### ISSUE TITLE
Update `image alt` icons for internationalization 

### ISSUE THREAD

**Issue by alekmackie** [Shopify/polaris-icons#81]
Let's update this `image alt` minor and major with something that's doesn't have different meanings in other languages.

Minor:
![](https://screenshot.click/9mfh6.jpg)

Major:
![](https://screenshot.click/tpz65.jpg)

**Comment by kaelig** [comment]
Closing this as this it hasn't been touched in more than 1/2 year and this seems low impact. Feel free to reopen if you have the bandwidth to carry this work through.
