### ISSUE TITLE
Partner Onboarding: options to select

### ISSUE THREAD

**Issue by alekmackie** [Shopify/polaris-icons#93]
This was originally an illustration request.  Porting it over here!  

@jesstam is looking to implement some icons for wayfinding purposes on the Partner Onboarding page (icons in screenshot are placeholders):

![](https://screenshot.click/Screen_Shot_2018-11-14_at_12.59.40_PM.png)

1. "Build apps for clients or the Shopify App Store": the `apps` icon works for me ✅ 
2. "Work with your client to build a new store": perhaps the `add, new` icon?  This option's all about "make a new store".  

![](https://screenshot.click/Screen_Shot_2018-11-14_at_12.54.03_PM.png)

3. "Work with your client to improve their existing store": this one's saying "improve a store", so I'm not sure if we have any existing icons that fit well metaphorically...  If not `tools`, then perhaps this needs to be a new icon that says "improve" or "make better" or something.  

![](https://screenshot.click/Screen_Shot_2018-11-14_at_12.53.51_PM.png)

4. "Become a Shopify Affiliate": the `affiliate` icon works ✅ 

Any thoughts, @Shopify/icon-reviewer?  I'm uncertain about 2 and 3.

**Comment by kaelig** [comment]
Closing this submission for inactivity as it was last updated more than 1/2 year ago. Please reopen if this is still current and resources will be available to pick this up.
