### ISSUE TITLE
Partner Onboarding - Recommended Resources Icon 

### ISSUE THREAD

**Issue by jesstam** [Shopify/polaris-icons#94]
#### What’s your name?
Jessica Tam

#### Slack handle
@Jessica Tam
#### What team / project is this for?
Partner Onboarding 

#### When would you like it by?
20/11/2018

#### What’s your request?

Looking for icons to represent 
- Blogs (Holly suggested something similar to the read minor icon) 
- Docs (Holly mentioned i can use the notes icon for this) 
- Partner Academy  (maybe a graduation cap for this icon?) 

Partner Onboarding is providing recommended resources and we'd like to have icons to identify what kind of resource is being recommended. As below 

<img width="651" alt="screen shot 2018-11-15 at 11 18 27 am" src="https://user-images.githubusercontent.com/28612325/48566202-367c0200-e8c8-11e8-9729-1eef7be70244.png">

It is important to have icons to differentiate the different types of resources as they are all very different in the way it helps the partners. Docs are more instructional/facts, and blogs are more supplementary, suggested reading, and partner academy are the courses we created to help our partner succeed.

**Comment by kaelig** [comment]
Closing this submission for inactivity as it was last updated more than 1/2 year ago.
